### ISSUE TITLE
Convert app server to the new Express template

### ISSUE THREAD

**Issue by seanwash** [seanwash/rodinia-report-web#26]
This should allow us to make our own API routes so that we can do things like have an endpoint for fetching story metadata.

### Todo

- [x] Copy over `/server` dir
- [x] Update remix config
- [x] Update package.json scripts
- [x] Update gitignore to ignore the generated build directories

### Dependencies

- remix-run/express
- remix-run/node
- remix-run/react
- compression
- express
- morgan
