### ISSUE TITLE
Remove express template and use remix server

### ISSUE THREAD

**Issue by seanwash** [seanwash/rodinia-report-web#38]
The main motivation for this is to just keep things simple. Right now we're having to juggle running the express app, remix app, and the styles and the dev experience isn't great. Also, having the express api routes available pushes me away from the remix philosophy.

## Todo

- [x] Remove server type check from pipeline
- [x] Update package.json
- [x] Remove server dir

**Comment by seanwash** [comment]
cc @chrsgrffth
